### ISSUE TITLE
Add animation for conch shell string being pulled when the user presses the ask button

### ISSUE THREAD

**Issue by TylerFlar** [cse110-sp23-group8/8-ball#14]
## Description:

We want to add an animation for pulling the Magic Conch Shell string when the user presses the ask button. You have the freedom to choose the implementation method, and you can consult AI for ideas if needed. One suggestion is to use a GIF to achieve the desired effect, but you may also consider other approaches.

## Tasks:

1. Find or create a suitable animation of the Magic Conch Shell string being pulled (GIF or another format, depending on your chosen implementation).
2. Implement the animation in the HTML, CSS, and Javascript code, ensuring it plays when the ask button is pressed.

Create a pull request for review once the changes are made.

**Comment by masteryangz** [comment]
@TylerFlar if we can't add animation, then I think we can change the image of the magic conch so that when the user hovers on the conch, the conch is an image ready to be pulled, and when the user clicks the conch, the conch is the image being pulled.
original state: ![original state](https://user-images.githubusercontent.com/108481340/233869347-68c4bb40-7387-4509-9ca1-01fa0c34a206.png), hover: ![hover](https://user-images.githubusercontent.com/108481340/233869411-1a346b32-e5a4-455a-a007-6287c1e463f9.png), click: ![click](https://user-images.githubusercontent.com/108481340/233869444-a24e17ba-a05a-4243-81ba-15eb98e83bad.png)

**Comment by masteryangz** [comment]
Similar to this, we can also update the characters so that the characters are more interactive.
